### PR TITLE
Fix ripple effect on safari and firefox browsers

### PR DESCRIPTION
**Pull request by paulino-corujo**
@manolakis @EfrenRey

### CODE REVIEW

**Comment by manolakis** [comment]
ack

**Comment by allyourbotsarebelongtous** [comment]
Deployed test instance is available at http://ek-83.internal.elastickube.com

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ek_pull_request/96/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Build was ABORTED. See http://jenkins.elasticbox.com/job/ek_pull_request/104/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://elasticbox.com/services/instances/i-xlpv0t

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ek_pull_request/111/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://elasticbox.com/services/instances/i-ls8d4l

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ek_pull_request/119/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://elasticbox.com/services/instances/i-zr4ufy

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ek_pull_request/129/ for more details.

**Comment by arnaud-elasticbox** [comment]
Jenkins, test this please.

**Comment by allyourbotsarebelongtous** [comment]
Deployed test instance is available at http://ek-83.internal.elastickube.com

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/ek_pull_request/144/ for more details.

**Pull request merged**
