### PR TITLE
Install MongoDB shell with --force-yes option

### PR DESCRIPTION
**Pull request by arnaud-elasticbox**
The package signature is incorrect

@albertoarias @osanjuan the signature for MongoDB package is incorrect. It happened in the past so I have added a workaround. We can remove it when the signature is fixed.

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ek_pull_request/179/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ek_pull_request/181/ for more details.

**Comment by arnaud-elasticbox** [comment]
Jenkins, test this please.

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ek_pull_request/182/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Deployed test instance is available at http://ek-114.internal.elastickube.com

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ek_pull_request/183/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ek_pull_request/184/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Instance i-hcp6mb couldnt be deleted. It requires manual deletion

**Comment by allyourbotsarebelongtous** [comment]
Instance i-ycb33m couldnt be deleted. It requires manual deletion

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://elasticbox.com/services/instances/i-hcp6mb, https://elasticbox.com/services/instances/i-5upeab, https://elasticbox.com/services/instances/i-ycb33m

**Comment by allyourbotsarebelongtous** [comment]
Deployed test instance is available at http://ek-114.internal.elastickube.com

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ek_pull_request/185/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://elasticbox.com/services/instances/i-xq2yxp

**Pull request merged**
