### PR TITLE
Add sub filters for Pod status in instances view

### PR DESCRIPTION
**Pull request by paulino-corujo**
@manolakis

### CODE REVIEW

**Comment by albertoarias** [comment]
@paulino-corujo Please rebase so we can get the test instance

**Comment by paulino-corujo** [comment]
@albertoarias done!

**Comment by allyourbotsarebelongtous** [comment]
Deployed test instance is available at http://ek-63.internal.elastickube.com

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ek_pull_request/51/ for more details.

**Comment by albertoarias** [comment]
Errors
image

**Comment by albertoarias** [comment]
@paulino-corujo I got a ton of errors when I deployed one of the charts

**Comment by paulino-corujo** [comment]
@albertoarias this error seems to be related with the fact that there is no containerID until the container is in Running status. It is not related with this PR so I opened a fix here: https://github.com/ElasticBox/elastickube/pull/76

**Comment by arnaud-elasticbox** [comment]
Jenkins, test this please.

**Comment by allyourbotsarebelongtous** [comment]
Deployed test instance is available at http://ek-63.internal.elastickube.com

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/ek_pull_request/67/ for more details.

**Comment by arnaud-elasticbox** [comment]
@manolakis can you review?

**Comment by manolakis** [comment]
ACK

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://elasticbox.com/services/instances/i-5zjugw

**Pull request merged**
