### PR TITLE
Allow unicode characters in signup form

### PR DESCRIPTION
**Pull request by paulino-corujo**
@EfrenRey @gsanchezu @manolakis

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Deployed test instance is available at http://ek-85.internal.elastickube.com

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ek_pull_request/99/ for more details.

**Comment by EfrenRey** [comment]
@paulino-corujo On Google auth we are updating the ```firstname``` and ```lastname``` with the info retrieved in token. What would happen if this info has that invalid characters? Probably we should handle that characters also in backend.

**Comment by paulino-corujo** [comment]
@EfrenRey you are right, I have removed the character blacklist

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://elasticbox.com/services/instances/i-jugoe4

**Comment by allyourbotsarebelongtous** [comment]
Build was ABORTED. See http://jenkins.elasticbox.com/job/ek_pull_request/102/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ek_pull_request/109/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://elasticbox.com/services/instances/i-5lz8a2

**Comment by allyourbotsarebelongtous** [comment]
Deployed test instance is available at http://ek-85.internal.elastickube.com

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ek_pull_request/112/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Deployed test instance is available at http://ek-85.internal.elastickube.com

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/ek_pull_request/118/ for more details.

**Comment by manolakis** [comment]
ACK

**Comment by manolakis** [comment]
ACK

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://elasticbox.com/services/instances/i-k0dnqa

**Pull request merged**
