### PR TITLE
Test CI

### PR DESCRIPTION
**Pull request by davisein**
Testing the CI on Jenkins. Based on #68

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Deployed test instance is available at http://ek-72.internal.elastickube.com

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ek_pull_request/31/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Deployed test instance is available at http://ek-72.internal.elastickube.com

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ek_pull_request/32/ for more details.

**Comment by davisein** [comment]
jenkins, test this please

**Comment by allyourbotsarebelongtous** [comment]
Deployed test instance is available at http://ek-72.internal.elastickube.com

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ek_pull_request/33/ for more details.

**Comment by davisein** [comment]
jenkins, test this please

**Comment by allyourbotsarebelongtous** [comment]
Deployed test instance is available at http://ek-72.internal.elastickube.com

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ek_pull_request/35/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://elasticbox.com/services/instances/i-lscsq8

**Pull request closed without merging**
