### PR TITLE
[DO NOT MERGE] Feature/dashboard

### PR DESCRIPTION
**Pull request by paulino-corujo**
@albertoarias @arnaud-elasticbox @mattnickles 

This is a first version of the dashboard, some issues to be fixed:

- Although the initial data is real data. Realtime data is simulated (still pending of reviewing the metrics watcher).
- The initial data jumps back in time sometimes because the metrics are not currently sorted by timestamp.
- The graphics for the Replication controllers at the bottom of the page have to be removed as we can not retrieve that data from the heapster API, maybe we can include another interesting graphs or reorganize the charts layout...
- The graph will not be an infinite chart, as a "garbage collector" will be implemented. In the UI an overflow control will be implemented to prevent the chart become slow.
- I expect to implement a smooth transition flow for the chart.
- The numbers in the y-axis are not under the tick lines because d3 is not reescaling well when the labels are moved. I will try to explore a solution (low priority)

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Deployed test instance is available at http://ek-74.internal.elastickube.com

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ek_pull_request/52/ for more details.

**Comment by albertoarias** [comment]
Lots of errors deploying 
image

**Comment by allyourbotsarebelongtous** [comment]
Deployed test instance is available at http://ek-74.internal.elastickube.com

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/ek_pull_request/61/ for more details.

**Comment by paulino-corujo** [comment]
jenkins, test this please

**Comment by allyourbotsarebelongtous** [comment]
Deployed test instance is available at http://ek-74.internal.elastickube.com

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/ek_pull_request/62/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Deployed test instance is available at http://ek-74.internal.elastickube.com

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/ek_pull_request/81/ for more details.

**Comment by albertoarias** [comment]
@arnaud-elasticbox @paulino-corujo Is this done?

**Comment by arnaud-elasticbox** [comment]
@albertoarias this part is only the UI, I know @paulino-corujo still need to fix the update metrics in realtime. The fix for this into the backend is also in https://github.com/ElasticBox/elastickube/pull/77

**Comment by paulino-corujo** [comment]
@albertoarias @arnaud-elasticbox We can close this PR. I will create a new PR with the realtime, and other improvements like responsive line chart behaviour once the PR https://github.com/ElasticBox/elastickube/pull/77 is merged.

**Comment by manolakis** [comment]
UI looks good

**Comment by albertoarias** [comment]
@paulino-corujo is this ready to be merged?

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://elasticbox.com/services/instances/i-e4l57y

**Comment by paulino-corujo** [comment]
I'm going to close this PR and open a new one with the latest changes after rebasing current master

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://elasticbox.com/services/instances/i-31994d

**Comment by allyourbotsarebelongtous** [comment]
Build was ABORTED. See http://jenkins.elasticbox.com/job/ek_pull_request/85/ for more details.

**Pull request closed without merging**
