### PR TITLE
Add dashboard tab

### PR DESCRIPTION
**Pull request by paulino-corujo**
@albertoarias @mattnickles @manolakis

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Deployed test instance is available at http://ek-81.internal.elastickube.com

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ek_pull_request/88/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://elasticbox.com/services/instances/i-i1pel8

**Comment by allyourbotsarebelongtous** [comment]
Deployed test instance is available at http://ek-81.internal.elastickube.com

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ek_pull_request/93/ for more details.

**Comment by arnaud-elasticbox** [comment]
@paulino-corujo it needs to be rebased. I fixed the PR instance box so it should be working after rebasing.

**Comment by albertoarias** [comment]
@paulino-corujo please rebase

**Comment by allyourbotsarebelongtous** [comment]
Deployed test instance is available at http://ek-81.internal.elastickube.com

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ek_pull_request/100/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Deployed test instance is available at http://ek-81.internal.elastickube.com

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ek_pull_request/101/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Build was ABORTED. See http://jenkins.elasticbox.com/job/ek_pull_request/106/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://elasticbox.com/services/instances/i-ku4s3t

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ek_pull_request/115/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Deployed test instance is available at http://ek-81.internal.elastickube.com

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/ek_pull_request/121/ for more details.

**Comment by manolakis** [comment]
ACK

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://elasticbox.com/services/instances/i-xg99me

**Pull request merged**
