### PR TITLE
Add absolute import

### PR DESCRIPTION
**Pull request by davisein**
Avoid implicit relative import

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ek_pull_request/28/ for more details.

**Comment by davisein** [comment]
jenkins, test this please

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ek_pull_request/29/ for more details.

**Comment by davisein** [comment]
jenkins, test this please

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ek_pull_request/30/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://elasticbox.com/services/instances/i-qfq59t

**Pull request closed without merging**
