### PR TITLE
Add blur and space stroke events to finalise invitation email edition

### PR DESCRIPTION
**Pull request by paulino-corujo**
@manolakis

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ek_pull_request/23/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ek_pull_request/24/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://elasticbox.com/services/instances/i-i4n370

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ek_pull_request/25/ for more details.

**Comment by arnaud-elasticbox** [comment]
@manolakis test failures are not related, you can review this.

**Comment by arnaud-elasticbox** [comment]
Jenkins, test this please.

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ek_pull_request/68/ for more details.

**Comment by arnaud-elasticbox** [comment]
@paulino-corujo can you rebase it so we have a PR instance to test?

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ek_pull_request/76/ for more details.

**Comment by paulino-corujo** [comment]
jenkins, test this please

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ek_pull_request/78/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://elasticbox.com/services/instances/i-vo8god

**Comment by allyourbotsarebelongtous** [comment]
Deployed test instance is available at http://ek-70.internal.elastickube.com

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ek_pull_request/79/ for more details.

**Comment by paulino-corujo** [comment]
jenkins, test this please

**Comment by allyourbotsarebelongtous** [comment]
Deployed test instance is available at http://ek-70.internal.elastickube.com

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/ek_pull_request/80/ for more details.

**Comment by manolakis** [comment]
ACK

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://elasticbox.com/services/instances/i-h0eqo1

**Pull request merged**
