### PR TITLE
[EBE-3840] [DONT MERGE] Redirect to validate account or request invite from login

### PR DESCRIPTION
**Pull request by EfrenRey**
@manolakis @albertoarias 

Improvements when login with password method:
- Fix the javascript error when a user introduce a bad password
- When a invited user (but not validated) try to login, is redirected to "request an invitation" page
- When a no registered user try to login, is redirected to "request an invitation" page

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ek_deploy_kubernetes/6/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ek_pull_request/174/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ek_deploy_kubernetes/7/ for more details.

**Comment by albertoarias** [comment]
@EfrenRey please update

**Comment by EfrenRey** [comment]
@albertoarias Updated.

Please, read the description at the beginning to check if you agree with the page redirections. Thanks.

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ek_pull_request/178/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://elasticbox.com/services/instances/i-l0puwi

**Pull request merged**
