### PR TITLE
Upgrade Kubernetes to v1.3.0:

### PR DESCRIPTION
**Pull request by arnaud-elasticbox**
- Update docker daemon to 1.10
- Add vagrant user to docker group
- Update nodejs version to v4.4.7 (LTS)
- Fix alias to run tests
- Update Heapster artifacts to recommended versions for
Kubernetes v1.3.0

### CODE REVIEW

**Comment by arnaud-elasticbox** [comment]
@albertoarias @osanjuan @manolakis 

This is also fixing the NodeJS version issue as well well as upgrading Heapster related components to the recommended versions.

I tested it locally and I can see all the metrics for Container and Namespace properly into the dashboard.

**Comment by allyourbotsarebelongtous** [comment]
Build was ABORTED. See http://jenkins.elasticbox.com/job/ek_pull_request/152/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ek_pull_request/153/ for more details.

**Comment by arnaud-elasticbox** [comment]
Jenkins, test this please.

**Comment by allyourbotsarebelongtous** [comment]
Deployed test instance is available at http://ek-107.internal.elastickube.com

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/ek_pull_request/154/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://elasticbox.com/services/instances/i-zp0qgc

**Pull request merged**
