### PR TITLE
Fix CairoSVG library dependency to latest compatible version 

### PR DESCRIPTION
**Pull request by gsanchezu**
For Python 2.7 the latest CairoSVG compatible version is fixed to 1.x, since version 2.x is for Python 3.x only.

@davisein, 👍?

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ek_pull_request/196/ for more details.

**Comment by gsanchezu** [comment]
Jenkins test this please

**Comment by allyourbotsarebelongtous** [comment]
Deployed test instance is available at http://ek-125.internal.elastickube.com

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ek_pull_request/197/ for more details.

**Comment by gsanchezu** [comment]
Jenkins, test this please, again

**Comment by allyourbotsarebelongtous** [comment]
Deployed test instance is available at http://ek-125.internal.elastickube.com

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ek_pull_request/198/ for more details.

**Comment by DiegoSanjuan** [comment]
Jenkins, test this please.

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See https://jenkins.elasticbox.com/job/ek_pull_request/199/ for more details.

**Comment by gsanchezu** [comment]
Jenkins test this please, again!

**Comment by allyourbotsarebelongtous** [comment]
Deployed test instance is available at http://ek-125.internal.elastickube.com

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See https://jenkins.elasticbox.com/job/ek_pull_request/200/ for more details.

**Comment by gsanchezu** [comment]
Jenkins test this please, again 2

**Comment by allyourbotsarebelongtous** [comment]
Deployed test instance is available at http://ek-125.internal.elastickube.com

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See https://jenkins.elasticbox.com/job/ek_pull_request/201/ for more details.

**Comment by gsanchezu** [comment]
Race condition? Jenkins test this please, again 3

**Comment by allyourbotsarebelongtous** [comment]
Deployed test instance is available at http://ek-125.internal.elastickube.com

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See https://jenkins.elasticbox.com/job/ek_pull_request/202/ for more details.

**Comment by gsanchezu** [comment]
Jenkins test this please, again 4, with a new PR instance

**Comment by allyourbotsarebelongtous** [comment]
Deployed test instance is available at http://ek-125.internal.elastickube.com

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See https://jenkins.elasticbox.com/job/ek_pull_request/203/ for more details.

**Comment by gsanchezu** [comment]
Jenkins test this please, again 5, with the new PR instance

**Comment by allyourbotsarebelongtous** [comment]
Deployed test instance is available at http://ek-125.internal.elastickube.com

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See https://jenkins.elasticbox.com/job/ek_pull_request/204/ for more details.

**Comment by gsanchezu** [comment]
Jenkins test this please, again 6, with the new PR instance reconfigured

**Comment by allyourbotsarebelongtous** [comment]
Deployed test instance is available at http://ek-125.internal.elastickube.com

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See https://jenkins.elasticbox.com/job/ek_pull_request/205/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Deployed test instance is available at http://ek-125.internal.elastickube.com

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See https://jenkins.elasticbox.com/job/ek_pull_request/206/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Deployed test instance is available at http://ek-125.internal.elastickube.com

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See https://jenkins.elasticbox.com/job/ek_pull_request/207/ for more details.

**Comment by gsanchezu** [comment]
Hey @davisein, I've included the changes we did this morning for my DevEnv to work to this pending PR, to check if the tests still fail, and now instead of 2 failed test we have some more! Could you please take a look whenever you can?

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://elasticbox.com/services/instances/i-8fk7ao, https://elasticbox.com/services/instances/i-dkikoc, https://elasticbox.com/services/instances/i-wvbh6t

**Comment by allyourbotsarebelongtous** [comment]
Deployed test instance is available at http://ek-125.internal.elastickube.com

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See https://jenkins.elasticbox.com/job/ek_pull_request/208/ for more details.

**Comment by davisein** [comment]
👍

**Comment by DiegoSanjuan** [comment]
ACK

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://elasticbox.com/services/instances/i-si7f4v

**Pull request merged**
