### PR TITLE
Refactor tests structure

### PR DESCRIPTION
**Pull request by arnaud-elasticbox**
Add pylon script
Fix minor pylon issues

@albertoarias

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ek_pull_request/63/ for more details.

**Comment by arnaud-elasticbox** [comment]
Jenkins, test this please

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ek_pull_request/64/ for more details.

**Comment by arnaud-elasticbox** [comment]
Jenkins, test this please.

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ek_pull_request/65/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Deployed test instance is available at http://ek-77.internal.elastickube.com

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/ek_pull_request/71/ for more details.

**Comment by arnaud-elasticbox** [comment]
Jenkins, test this please.

**Comment by arnaud-elasticbox** [comment]
@paulino-corujo it includes the fix for receiving update events in metrics watcher

**Comment by allyourbotsarebelongtous** [comment]
Deployed test instance is available at http://ek-77.internal.elastickube.com

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ek_pull_request/73/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Build was ABORTED. See http://jenkins.elasticbox.com/job/ek_pull_request/74/ for more details.

**Comment by arnaud-elasticbox** [comment]
Jenkins, test this please.

**Comment by allyourbotsarebelongtous** [comment]
Deployed test instance is available at http://ek-77.internal.elastickube.com

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/ek_pull_request/75/ for more details.

**Comment by albertoarias** [comment]
@arnaud-elasticbox I don't like the inheritance pattern for test cases. I would rather use the functions directly to avoid having a shadow context stored in the root class during the test run.

Thoughts?

**Comment by allyourbotsarebelongtous** [comment]
Instance i-tld42d couldnt be deleted. It requires manual deletion

**Comment by allyourbotsarebelongtous** [comment]
Instance i-y5o6xx couldnt be deleted. It requires manual deletion

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://elasticbox.com/services/instances/i-tld42d, https://elasticbox.com/services/instances/i-h0ber9, https://elasticbox.com/services/instances/i-y5o6xx

**Pull request merged**
