### PR TITLE
Update Kubernetes version to 1.3.2

### PR DESCRIPTION
**Pull request by arnaud-elasticbox**

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ek_pull_request/157/ for more details.

**Comment by arnaud-elasticbox** [comment]
Jenkins, test this please.

**Comment by allyourbotsarebelongtous** [comment]
Deployed test instance is available at http://ek-109.internal.elastickube.com

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/ek_pull_request/160/ for more details.

**Comment by arnaud-elasticbox** [comment]
@albertoarias ready to merge.

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://elasticbox.com/services/instances/i-5hgg2s

**Pull request merged**
