### PR TITLE
Explain where the deployment script comes from

### PR DESCRIPTION
**Pull request by albertoarias**
@colemickens FYI

### CODE REVIEW

**Comment by colemickens** [comment]
👍 thank you!

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ek_pull_request/134/ for more details.

**Comment by albertoarias** [comment]
Jenkins test this please.

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ek_pull_request/135/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://elasticbox.com/services/instances/i-k5tikq

**Pull request merged**
