### PR TITLE
Fix devenv default users access

### PR DESCRIPTION
**Pull request by paulino-corujo**
@arnaud-elasticbox @albertoarias

### CODE REVIEW

**Comment by arnaud-elasticbox** [comment]
ack

**Comment by allyourbotsarebelongtous** [comment]
Deployed test instance is available at http://ek-80.internal.elastickube.com

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ek_pull_request/86/ for more details.

**Comment by arnaud-elasticbox** [comment]
Jenkins, test this please.

**Comment by allyourbotsarebelongtous** [comment]
Deployed test instance is available at http://ek-80.internal.elastickube.com

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ek_pull_request/87/ for more details.

**Comment by albertoarias** [comment]
Jenkins test this please.

**Comment by allyourbotsarebelongtous** [comment]
Deployed test instance is available at http://ek-80.internal.elastickube.com

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ek_pull_request/90/ for more details.

**Comment by arnaud-elasticbox** [comment]
Jenkins, test this please.

**Comment by allyourbotsarebelongtous** [comment]
Deployed test instance is available at http://ek-80.internal.elastickube.com

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ek_pull_request/92/ for more details.

**Comment by arnaud-elasticbox** [comment]
@paulino-corujo this branch needs to be rebased, to have the latest auth code.

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://elasticbox.com/services/instances/i-saxm7u

**Pull request merged**
