### PR TITLE
Reconnect watch namespaces

### PR DESCRIPTION
**Pull request by arnaud-elasticbox**
When http connection is closed properly, reconnect anyway
Add time to log messages

@albertoarias @osanjuan connection can be also closed properly, so we should also reconnect into that case.

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Deployed test instance is available at http://ek-95.internal.elastickube.com

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/ek_pull_request/131/ for more details.

**Comment by arnaud-elasticbox** [comment]
@albertoarias @osanjuan I am almost sure this is causing the issue reported here:
https://github.com/ElasticBox/elastickube/issues/89

**Comment by paulino-corujo** [comment]
ACK

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://elasticbox.com/services/instances/i-g6pk09

**Pull request merged**
