### PR TITLE
[EBE-3828] Fixed login form labels overlapping

### PR DESCRIPTION
**Pull request by jllr**
@EfrenRey 

https://elasticbox.atlassian.net/browse/EBE-3828

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ek_pull_request/148/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://elasticbox.com/services/instances/i-4k7kai

**Comment by allyourbotsarebelongtous** [comment]
Deployed test instance is available at http://ek-105.internal.elastickube.com

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/ek_pull_request/149/ for more details.

**Comment by EfrenRey** [comment]
ACK

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://elasticbox.com/services/instances/i-szwhrm

**Pull request merged**
