### PR TITLE
Change default charts repo to point to Kubernetes one

### PR DESCRIPTION
**Pull request by gsanchezu**
@davisein , 👍?

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See https://jenkins.elasticbox.com/job/ek_pull_request/209/ for more details.

**Comment by davisein** [comment]
The code looks good. @gsanchezu Does the code works with the newer format? Have you checked that it works well with the newer charts?

**Comment by gsanchezu** [comment]
Hey @davisein! I wanted to test it with the PR instance, which in fact failed to deploy... I just fixed it with a re-deploy, so we may see how it goes with the next job run.

I also took a look to the new repo and, apart from the directory structure change (a new parent directory called 'stable') that might need to be addressed when downloading charts, I reviewed some charts details and I realized that many of them are using Kubernetes resources that are not yet supported by ElasticKube (such as Ingress), so we rather just redirect the default charts repo to the 'helm/charts-classic' for now... Thanks!

**Comment by allyourbotsarebelongtous** [comment]
Deployed test instance is available at http://ek-135.internal.elastickube.com

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See https://jenkins.elasticbox.com/job/ek_pull_request/210/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://elasticbox.com/services/instances/i-cgkyyq

**Pull request merged**
